// Code generated by MockGen. DO NOT EDIT.
// Source: daemonset.go

// Package daemonset is a generated GoMock package.
package daemonset

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
	v10 "sigs.k8s.io/node-feature-discovery-operator/api/v1"
)

// MockDaemonsetAPI is a mock of DaemonsetAPI interface.
type MockDaemonsetAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonsetAPIMockRecorder
}

// MockDaemonsetAPIMockRecorder is the mock recorder for MockDaemonsetAPI.
type MockDaemonsetAPIMockRecorder struct {
	mock *MockDaemonsetAPI
}

// NewMockDaemonsetAPI creates a new mock instance.
func NewMockDaemonsetAPI(ctrl *gomock.Controller) *MockDaemonsetAPI {
	mock := &MockDaemonsetAPI{ctrl: ctrl}
	mock.recorder = &MockDaemonsetAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonsetAPI) EXPECT() *MockDaemonsetAPIMockRecorder {
	return m.recorder
}

// SetTopologyDaemonsetAsDesired mocks base method.
func (m *MockDaemonsetAPI) SetTopologyDaemonsetAsDesired(ctx context.Context, nfdInstance *v10.NodeFeatureDiscovery, topologyDS *v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopologyDaemonsetAsDesired", ctx, nfdInstance, topologyDS)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTopologyDaemonsetAsDesired indicates an expected call of SetTopologyDaemonsetAsDesired.
func (mr *MockDaemonsetAPIMockRecorder) SetTopologyDaemonsetAsDesired(ctx, nfdInstance, topologyDS interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopologyDaemonsetAsDesired", reflect.TypeOf((*MockDaemonsetAPI)(nil).SetTopologyDaemonsetAsDesired), ctx, nfdInstance, topologyDS)
}

// SetWorkerDaemonsetAsDesired mocks base method.
func (m *MockDaemonsetAPI) SetWorkerDaemonsetAsDesired(ctx context.Context, nfdInstance *v10.NodeFeatureDiscovery, workerDS *v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkerDaemonsetAsDesired", ctx, nfdInstance, workerDS)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkerDaemonsetAsDesired indicates an expected call of SetWorkerDaemonsetAsDesired.
func (mr *MockDaemonsetAPIMockRecorder) SetWorkerDaemonsetAsDesired(ctx, nfdInstance, workerDS interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerDaemonsetAsDesired", reflect.TypeOf((*MockDaemonsetAPI)(nil).SetWorkerDaemonsetAsDesired), ctx, nfdInstance, workerDS)
}
