apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-topology-updater
spec:
  selector:
    matchLabels:
      app: nfd-topology-updater
  template:
    metadata:
      labels:
        app: nfd-topology-updater
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: nfd-topology-updater
      containers:
        - name: nfd-topology-updater
          image: registry.k8s.io/nfd/node-feature-discovery:v0.17.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            grpc:
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          command:
            - "nfd-topology-updater"
          args: []
          resources:
            limits:
              cpu: 100m
              memory: 60Mi
            requests:
              cpu: 50m
              memory: 40Mi
          ports:
            - name: metrics
              containerPort: 8081
