apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-topology-updater
spec:
  selector:
    matchLabels:
      app: nfd-topology-updater
  template:
    metadata:
      labels:
        app: nfd-topology-updater
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: nfd-topology-updater
      containers:
        - name: nfd-topology-updater
          image: registry.k8s.io/nfd/node-feature-discovery:v0.12.3
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-topology-updater"
          args: []
