apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      serviceAccount: nfd-worker
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nfd-worker
          image: registry.k8s.io/nfd/node-feature-discovery:v0.15.3
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-worker"
          args:
            - "-server=nfd-master:8080"
          ports:
            - name: metrics
              containerPort: 8081
