ARG BUILDER_IMAGE
FROM ${BUILDER_IMAGE} as builder

# Install tools
RUN --mount=type=cache,target=/go/pkg/mod/ \
    go install github.com/vektra/mockery/v2@v2.52.2 && \
    go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.3 && \
    go install golang.org/x/tools/cmd/goimports@v0.25.0

# Expect to be working with nfd
WORKDIR /go/node-feature-discovery

# We need to set the /go/node-feature-discovery directory as a safe directory.
# This allows git commands to run in the container on MacOS systems.
RUN git config --file=/.gitconfig --add safe.directory /go/node-feature-discovery
