ARG BUILDER_IMAGE
FROM ${BUILDER_IMAGE} as builder

# Install tools
RUN go install github.com/vektra/mockery/v2@v2.25.1 && \
    go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3 && \
    git clone https://github.com/kubernetes/code-generator -b v0.27.1 --depth 1 && \
    go install k8s.io/code-generator/cmd/go-to-protobuf/...@v0.27.1 && \
    go install golang.org/x/tools/cmd/goimports@v0.8.0 && \
    go install github.com/golang/protobuf/protoc-gen-go@v1.4.3

RUN apt-get update && apt-get install unzip

RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip && \
    unzip protoc-22.3-linux-x86_64.zip -d /usr/local && \
    rm protoc-22.3-linux-x86_64.zip && \
    chmod a+x /usr/local/bin/protoc && \
    find /usr/local -type d | xargs chmod 755 && \
    find /usr/local -type f | xargs chmod a+r


# Expect to be working with nfd
WORKDIR /go/node-feature-discovery
