apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nfd-master
rules:
- apiGroups:
  - topology.node.k8s.io
  resources:
  - noderesourcetopologies
  verbs:
  - create
  - get
  - update

