apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfd-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nfd-master
subjects:
- kind: ServiceAccount
  name: nfd-master

