apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nfd-worker
rules:
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get