apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfd-worker
rules:
- apiGroups:
  - ""
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
