{
 "title": "Node Feature Discovery",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running nfd-masters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(nfd_master_build_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running nfd-workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(nfd_worker_build_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running nfd-gcs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(nfd_gc_build_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running nfd-topology-updaters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nfd_topology_updater_build_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "targets": [
    { "expr": "nfd_master_node_updates_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Objects GC'd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum by(kind) (nfd_gc_objects_deleted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node update errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nfd_master_node_update_failures_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "NodeFeatureRule errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "nfd_master_nodefeaturerule_processing_errors_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Topology-Updater scan errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(nfd_topology_updater_scan_errors_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "GC delete object errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum by(kind) (nfd_gc_object_delete_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feature discvery time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (nfd_worker_feature_discovery_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeFeatureRule processing time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (nfd_master_nodefeaturerule_processing_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node labels rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "nfd_master_node_labels_rejected_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Node extended resources rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "nfd_master_node_extendedresources_rejected_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Node taints rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "nfd_master_node_taints_rejected_total",
     "legendFormat": "total"
    }
   ]
  }
 ]
}