apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd
spec:
  selector:
    matchLabels:
      app: nfd
  template:
    metadata:
      labels:
        app: nfd
    spec:
      serviceAccount: nfd-master
      tolerations: []
      containers:
      - name: nfd-master
        image: registry.k8s.io/nfd/node-feature-discovery:v0.12.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["/usr/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["/usr/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        command:
        - "nfd-master"
      - name: nfd-worker
        image: registry.k8s.io/nfd/node-feature-discovery:v0.12.4
        imagePullPolicy: IfNotPresent
        command:
        - "nfd-worker"
        args: []
