apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- namespace.yaml
- prune-serviceaccount.yaml
- prune-clusterrole.yaml
- prune-clusterrolebinding.yaml
- master-job.yaml

components:
- ../../components/common
- ../../components/master-config
