apiVersion: batch/v1
kind: Job
metadata:
  name: nfd-master
  labels:
    app: nfd
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: nfd-prune
    spec:
      serviceAccount: nfd-master
      tolerations: []
      containers:
        - name: nfd-master
          image: registry.k8s.io/nfd/node-feature-discovery:v0.14.6
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-master"
          args:
            - "-prune"
      restartPolicy: Never

