source "https://rubygems.org"

# Use override plugin to drop incorrect dependency of jekyll-rtd-them on github-pages (~> 209)
# The original dep would allow github-pages v209.x but not v210 or later.
plugin 'bundler-override'
require File.join(Bundler::Plugin.index.load_paths("bundler-override")[0], "bundler-override") rescue nil
override 'jekyll-rtd-theme', :drop => "github-pages"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.10.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", "~> 232", group: :jekyll_plugins
gem "jekyll-github-metadata", git: "https://github.com/jekyll/github-metadata", ref: "e41276ff417a4aa4701bd617b5007c07e1e074e6", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

# kramdown v2 ships without the gfm parser by default. If you're using
# kramdown v1, comment out this line.
#gem "kramdown-parser-gfm"

gem "webrick", "~> 1.8"

gem 'jekyll-rtd-theme', '~> 2.0', '>= 2.0.10'
